default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: document_analyzer_development

test:
  <<: *default
  database: document_analyzer_test

production:
  <<: *default
  database: document_analyzer_production
  url: <%= ENV["DATABASE_URL"] %>
